### ISSUE TITLE
"Unfair" comparisons - why not compare against the runtime API's C++ wrappers?

### ISSUE THREAD

**Issue by eyalroz** [codeplaysoftware/SYCL-For-CUDA-Examples#7]
Your example programs compare SYCL against use of the CUDA Runtime API. However, would it not make more sense to compare against the [C++ wrappers](https://github.com/eyalroz/cuda-api-wrappers/issues) of the Runtime API?

It seems to me that would better clarify what using SYCL really means.

**Comment by Ruyk** [comment]
Not everyone uses those wrappers, we want to compare idiomatic CUDA to idiomatic SYCL.
SYCL is a fully-featured programming model that adds, among other things, targeting other platforms other than CUDA with the same C++ source and a standard programming model.
